### ISSUE TITLE
Using Slugma burner as a heating source for a boiler will only count 1 bar of heat regardless of heat level of slugma/amount of them.

### ISSUE THREAD

**Issue by ghost** [R3charged/Create-Slugma#10]
When placing down a slugma burner underneath a boiler it will only count the heat level as one like the campfire but if you give a slugma burner coal or blazecake it will not change the heat level of the boiler.

1. Create a normal blaze boiler set up.
2. replace the blazes with slugma
3. give the slugma a blaze cake
4. See error by looking at a boiler with goggles

**Comment by R3charged** [comment]
Patched in Release 1.0.3
